quali_variables:
  - FLAG_ELETRONICOS_3M
  - SATISFACAO_ULTIMA_COMPRA

quanti_variables:
  - IDADE_CLIENTE
  - RENDA_MENSAL_CLIENTE
  - BEHAVIOUR_SCORE_CLIENTE
  - QTD_TRANSACOES_3M
  - QTD_ITENS_3M
  - VALOR_GASTO_3M
  - TICKET_MEDIO_3M

target: VALOR_GASTO_PROX_12M

trained_model_file: models/trained/trained

production_model_file: models/production/model.pkl

train_data_path : 'datasets/Potencial_Novos_Clientes.txt'

predict_data_path : 'datasets/X_teste.csv'

result_data_path : 'datasets/results'

erro: 1000

models:
  - LINEAR
  - RIDGE